typography_spectrum: 0.31750061945058405
color:
  brandStrength: 0.8227178445085883
  lightness: 0.6567511248867959
  saturation: 0.217558705015108
  rhythmicContrast: 0.5090260002762079
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.5553198035340756
author:
  name: Douglas Horch
  email: doug@mappehomes.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/15e308ba-de8a-45b2-a39e-dd1487cd5888.jpg
name: Mappe | Denver
navigation:
  - name: Want to see all the homes for sale in Denver?
    url: 'http://jill.smartdenverhomesearch.com/'
    type: external
title: Mappe Real Estate
description: Put Yourself On The Map!
